version: '3'
services:
  web:
    image: docker pull romeoz/docker-phpfpm:5.4
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - /var/www:/var/www/app
  db:
    image: mariadb:10.1
    ports:
      -
    volumes:
      - /var/www:/var/www/app
      - /my/own/datadir:/var/lib/mysq
    environment:
      MYSQL_ROOT_PASSWORD: root

